project_id = "wcfflsfwhivbwnbkenva"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "http://localhost:4173/os/"
additional_redirect_urls = ["http://127.0.0.1:4173/os/"]

[storage]
enabled = true

