export const INVENTORY_TYPES=Object.freeze({ingredient:'Ingredientes',work_in_progress:'Productos en proceso',finished_good:'Productos terminados',packaging:'Empaques',utensil:'Utensilios',equipment:'Equipos'});
export const EVENT_TYPES=Object.freeze({purchase:'Compra',production:'Producción',consumption:'Consumo',waste:'Merma',adjustment:'Ajuste de inventario',transfer:'Transferencia'});
export const eventDelta=event=>event.type==='transfer'?0:Number(event.quantityDelta)||0;
export function projectInventory(items,events){return items.map(item=>{const movements=events.filter(event=>event.itemId===item.id).sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt)),stock=movements.reduce((total,event)=>total+eventDelta(event),Number(item.openingStock)||0);return {...item,stock,lastMovement:movements[0]||null}})}
export function inventoryAlerts(items,events){const projected=projectInventory(items,events),alerts=[];for(const item of projected){if(item.stock<=0)alerts.push({level:'critical',type:'out',itemId:item.id,message:`${item.name} está agotado.`});else if(item.stock<item.minimumStock)alerts.push({level:'warning',type:'low',itemId:item.id,message:`${item.name} está por debajo del stock mínimo.`});if(item.nextExpiry&&daysUntil(item.nextExpiry)<=3)alerts.push({level:'warning',type:'expiry',itemId:item.id,message:`${item.name} vence pronto.`})}for(const event of events.filter(event=>event.type==='waste'&&event.expectedQuantity)){const loss=Math.abs(eventDelta(event)),rate=loss/event.expectedQuantity*100;if(rate>=2)alerts.push({level:'warning',type:'waste',itemId:event.itemId,message:`Merma de ${rate.toFixed(1)}% registrada en ${event.label||'producción'}.`})}return alerts}
export const daysUntil=date=>Math.ceil((new Date(`${date}T23:59:59`)-new Date())/86400000);
export function yieldVariance(expected,actual){const difference=actual-expected;return {expected,actual,difference,percentage:expected?difference/expected*100:0,waste:Math.max(0,-difference)}}
export function createYieldEvents({itemId,expected,actual,unit,formulaVersion,productionOrderId,responsible,occurredAt=new Date().toISOString()}){const variance=yieldVariance(expected,actual),base={itemId,unit,formulaVersion,productionOrderId,responsible,occurredAt,expectedQuantity:expected,actualQuantity:actual};return [{id:`evt-${Date.now()}-production`,type:'production',quantityDelta:expected,label:'Rendimiento esperado',...base},...(variance.waste?[{id:`evt-${Date.now()}-waste`,type:'waste',quantityDelta:-variance.waste,label:'Diferencia de rendimiento',...base}]:[])]}
export function registerInventoryEvent(events,event){if(!EVENT_TYPES[event.type])throw new Error('Tipo de evento no válido.');if(!event.itemId)throw new Error('Selecciona un elemento.');if(!Number.isFinite(Number(event.quantityDelta)))throw new Error('La cantidad no es válida.');events.push({...event,id:event.id||`evt-${Date.now()}`,occurredAt:event.occurredAt||new Date().toISOString()});return events.at(-1)}
